{{- if .Values.demo.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "releasepulse.fullname" . }}-demo
  labels:
    {{- include "releasepulse.labels" . | nindent 4 }}
    app.kubernetes.io/component: demo
spec:
  type: ClusterIP
  selector:
    {{- include "releasepulse.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: demo
  ports:
    - name: http
      port: {{ .Values.demo.service.port }}
      targetPort: http
{{- end }}
