"""initial schema

Revision ID: e96f69f637c4
Revises: 
Create Date: 2026-06-26 10:33:57.263285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e96f69f637c4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services')),
    sa.UniqueConstraint('name', name=op.f('uq_services_name'))
    )
    op.create_table('deployments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('environment', sa.Text(), server_default='production', nullable=False),
    sa.Column('version', sa.Text(), nullable=True),
    sa.Column('commit_sha', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('reported_deployed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('effective_deployed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evaluation_status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('evaluation_reason', sa.Text(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("evaluation_status IN ('pending','evaluated_no_regression','evaluated_regression','insufficient_baseline','superseded','invalid')", name=op.f('ck_deployments_evaluation_status_allowed')),
    sa.CheckConstraint("source IN ('github-actions','argocd','manual')", name=op.f('ck_deployments_source_allowed')),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_deployments_service_id_services')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deployments')),
    sa.UniqueConstraint('source', 'external_id', name='uq_deployments_source_external_id')
    )
    op.create_index('ix_deployments_service_env_effective', 'deployments', ['service_id', 'environment', 'effective_deployed_at'], unique=False)
    op.create_table('endpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('environment', sa.Text(), server_default='production', nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('method', sa.Text(), server_default='GET', nullable=False),
    sa.Column('expected_status', sa.Integer(), server_default=sa.text('200'), nullable=False),
    sa.Column('check_interval_sec', sa.Integer(), server_default=sa.text('30'), nullable=False),
    sa.Column('timeout_sec', sa.Integer(), server_default=sa.text('10'), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latency_pct', sa.Numeric(), nullable=True),
    sa.Column('latency_floor_ms', sa.Integer(), nullable=True),
    sa.Column('error_delta', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('check_interval_sec >= 10', name=op.f('ck_endpoints_check_interval_min')),
    sa.CheckConstraint('expected_status BETWEEN 100 AND 599', name=op.f('ck_endpoints_expected_status_range')),
    sa.CheckConstraint('timeout_sec > 0', name=op.f('ck_endpoints_timeout_positive')),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_endpoints_service_id_services')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_endpoints')),
    sa.UniqueConstraint('service_id', 'environment', 'url', 'method', name='uq_endpoints_service_env_url_method')
    )
    op.create_table('checks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('endpoint_id', sa.UUID(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.Text(), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('tls_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("error_type IS NULL OR error_type IN ('timeout','dns_error','connection_refused','tls_error','unexpected_status','internal_error')", name=op.f('ck_checks_error_type_allowed')),
    sa.CheckConstraint('latency_ms IS NULL OR latency_ms >= 0', name=op.f('ck_checks_latency_nonnegative')),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], name=op.f('fk_checks_endpoint_id_endpoints')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checks'))
    )
    op.create_index('ix_checks_endpoint_id_checked_at', 'checks', ['endpoint_id', 'checked_at'], unique=False)
    op.create_table('deployment_endpoint_evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deployment_id', sa.UUID(), nullable=False),
    sa.Column('endpoint_id', sa.UUID(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('baseline_median_latency_ms', sa.Integer(), nullable=True),
    sa.Column('observed_median_latency_ms', sa.Integer(), nullable=True),
    sa.Column('baseline_error_rate', sa.Numeric(), nullable=True),
    sa.Column('observed_error_rate', sa.Numeric(), nullable=True),
    sa.Column('baseline_samples', sa.Integer(), nullable=False),
    sa.Column('observed_samples', sa.Integer(), nullable=False),
    sa.Column('observed_failed_checks', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("outcome IN ('regressed_latency','regressed_error','regressed_both','no_regression','insufficient_baseline','insufficient_observation','insufficient_successful_baseline','baseline_degraded','superseded')", name=op.f('ck_deployment_endpoint_evaluations_outcome_allowed')),
    sa.CheckConstraint('baseline_error_rate BETWEEN 0 AND 1', name=op.f('ck_deployment_endpoint_evaluations_baseline_error_rate_range')),
    sa.CheckConstraint('observed_error_rate BETWEEN 0 AND 1', name=op.f('ck_deployment_endpoint_evaluations_observed_error_rate_range')),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], name=op.f('fk_deployment_endpoint_evaluations_deployment_id_deployments')),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], name=op.f('fk_deployment_endpoint_evaluations_endpoint_id_endpoints')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deployment_endpoint_evaluations')),
    sa.UniqueConstraint('deployment_id', 'endpoint_id', name='uq_dee_deployment_endpoint')
    )
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('deployment_id', sa.UUID(), nullable=False),
    sa.Column('environment', sa.Text(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Text(), server_default='open', nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('open','acknowledged','resolved')", name=op.f('ck_incidents_status_allowed')),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], name=op.f('fk_incidents_deployment_id_deployments')),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_incidents_service_id_services')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents')),
    sa.UniqueConstraint('deployment_id', name=op.f('uq_incidents_deployment_id'))
    )
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending','sent','failed')", name=op.f('ck_alerts_status_allowed')),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_alerts_incident_id_incidents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts')),
    sa.UniqueConstraint('incident_id', 'channel', name='uq_alerts_incident_channel')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerts')
    op.drop_table('incidents')
    op.drop_table('deployment_endpoint_evaluations')
    op.drop_index('ix_checks_endpoint_id_checked_at', table_name='checks')
    op.drop_table('checks')
    op.drop_table('endpoints')
    op.drop_index('ix_deployments_service_env_effective', table_name='deployments')
    op.drop_table('deployments')
    op.drop_table('services')
    # ### end Alembic commands ###
